# -*- coding: utf-8 -*-
"""heat_exchanger_optimization.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11X7Gwqixu1yKr7KFchRuCB1l6faBwZmW
"""

# ==========================================
# PROJECT 2: SIMULATION + OPTIMIZATION
# ==========================================

import numpy as np
import matplotlib.pyplot as plt

# ================================
# STEP 1: DEFINE SYSTEM MODEL
# ================================

def efficiency_model(temp_diff, flow_rate):
    """
    Simulated efficiency model based on engineering intuition
    """

    # Efficiency increases with temperature difference
    # Efficiency decreases with high flow rate

    efficiency = (0.8 * (temp_diff / (temp_diff + 20))) * np.exp(-0.05 * flow_rate)

    return efficiency


# ================================
# STEP 2: GENERATE OPERATING RANGE
# ================================

temp_range = np.linspace(10, 100, 50)      # Temperature difference
flow_range = np.linspace(1, 10, 50)        # Flow rate

T, F = np.meshgrid(temp_range, flow_range)

E = efficiency_model(T, F)


# ================================
# STEP 3: 3D SURFACE PLOT
# ================================

fig = plt.figure()
ax = fig.add_subplot(111, projection='3d')

ax.plot_surface(T, F, E)

ax.set_xlabel("Temperature Difference")
ax.set_ylabel("Flow Rate")
ax.set_zlabel("Efficiency")

plt.title("Heat Exchanger Performance Surface")
plt.show()


# ================================
# STEP 4: FIND OPTIMAL CONDITIONS
# ================================

max_eff = np.max(E)
index = np.unravel_index(np.argmax(E), E.shape)

optimal_temp = T[index]
optimal_flow = F[index]

print("\nOPTIMAL CONDITIONS:")
print(f"Maximum Efficiency: {max_eff:.4f}")
print(f"Optimal Temperature Difference: {optimal_temp:.2f}")
print(f"Optimal Flow Rate: {optimal_flow:.2f}")


# ================================
# STEP 5: CONTOUR PLOT (EASIER VIEW)
# ================================

plt.figure()
contour = plt.contourf(T, F, E, levels=20)
plt.colorbar(contour)

plt.xlabel("Temperature Difference")
plt.ylabel("Flow Rate")
plt.title("Efficiency Contour Map")

plt.show()


# ================================
# STEP 6: INTERPRETATION
# ================================

print("\nINTERPRETATION:")

print("""
- Efficiency increases with higher temperature difference.
- Efficiency decreases with higher flow rate.
- Optimal region lies at high temperature difference and low flow rate.
- Trade-off exists between throughput (flow) and efficiency.
""")
# ================================
# STEP 7: CONSTRAINED OPTIMIZATION
# ================================

print("\nCONSTRAINED OPTIMIZATION:")

# Constraints
max_temp_allowed = 80
min_flow_required = 3

# Apply constraints
valid_indices = np.where((T <= max_temp_allowed) & (F >= min_flow_required))

E_valid = E[valid_indices]
T_valid = T[valid_indices]
F_valid = F[valid_indices]

# Find optimal under constraints
max_eff_constrained = np.max(E_valid)
index_c = np.argmax(E_valid)

optimal_temp_c = T_valid[index_c]
optimal_flow_c = F_valid[index_c]

print(f"Max Efficiency (Constrained): {max_eff_constrained:.4f}")
print(f"Optimal Temp (<=80): {optimal_temp_c:.2f}")
print(f"Optimal Flow (>=3): {optimal_flow_c:.2f}")

# ================================
# STEP 8: ML ON SIMULATION DATA
# ================================

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import PolynomialFeatures
from sklearn.metrics import r2_score

# Prepare dataset
X_data = np.column_stack((T.flatten(), F.flatten()))
y_data = E.flatten()

# Train-test split
X_train, X_test, y_train, y_test = train_test_split(X_data, y_data, test_size=0.2, random_state=42)

# Polynomial transformation
poly = PolynomialFeatures(degree=2)
X_train_poly = poly.fit_transform(X_train)
X_test_poly = poly.transform(X_test)

# Train model
model = LinearRegression()
model.fit(X_train_poly, y_train)

# Predictions
y_pred = model.predict(X_test_poly)

# Evaluate
r2 = r2_score(y_test, y_pred)

print("\nML MODEL PERFORMANCE ON SIMULATION DATA:")
print(f"R² Score: {r2:.4f}")